#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh

#Picom
picom &

# WorkSpaces
bspc monitor -d I II III IV V

# Other stuff
bspc config border_width        2
bspc config window_gap          16
bspc config top_padding         30
bspc config left_padding        0 
bspc config right_padding       0 
bspc config bottom_padding      0 
bspc config split_ratio         0.6
